### ISSUE TITLE
MDS is not a PCA nor SVD

### ISSUE THREAD

**Issue by amackey** [Victorian-Bioinformatics-Consortium/degust#43]
Your application says it's generating MDS plots, but it is not; an MDS plot (as in limma's plotMDS) is about representing fold-change distances between samples, without respect to variance explained. MDS dimensions do not have "variance explained", i.e. MDS 1 is no more or less important than MDS 2. Limma's plotMDS uses R's cmdscale() function which does not return any information about variance explained. But your tool is using SVD (akin to R's prcomp() function) to calculate a PCA plot, which does have a variance explained component. You'd do the community a favor by tightening your use of statistical language.  MDS and PCA are not interchangeable.

**Comment by drpowell** [comment]
MDS and PCA are indeed not the same thing, MDS can refer to several different techniques for dimensional scaling.    However, classical (Torgerson) MDS when using a Euclidean distance metric is equivalent to PCA, and thus it is reasonable to show the variance explained by each dimension.  The main reason I call it MDS in Degust rather than PCA is that the dimensions show a RMS of that dimension which is easier to interpret.  

Thanks for your feedback.

**Comment by amackey** [comment]
Sure -- but you're not performing an MDS (classical or otherwise) under the
hood, so why even call it that? Call it a PCA, and inform how you've
rescaled the PC axes. Just my two cents, looking to clarify usage. thanks
for the prompt reply! -Aaron

**Comment by drpowell** [comment]
It doesn't matter how it is implemented, it really is the same thing!  But your confusion is a very good point,  and I need to get some reasonable documentation written for exactly this type of thing.  Something for me to work on over the end-of-year break :)
